# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    rpi: { width: 800, height: 480 }
    pi_camera:
        output_dir: '%output_dir%'
        defaults:
            timeout: { command: '--timeout', model: 'range', default: 5000, min:1000, max: 30000, step: 1, compute: '*1000', label: 'retardateur'}
            sharpness: { command: '--sharpness', model: 'range', default: 0, min:-100, max: 100, step: 10, compute: '*1', label: 'netteté'}
            contrast: { command: '--contrast', model: 'range', default: 0, min:-100, max: 100, step: 10, compute: '*1', label: 'contraste'}
            brightness: { command: '--brightness', model: 'range', default: 50, min:0, max: 100, step: 10, compute: '*1', label: 'luminosité'}
            saturation: { command: '--saturation', model: 'range', default: 0, min:-100, max: 100, step: 10, compute: '*1', label: 'saturation'}
            quality: { command: '--quality', model: 'range', default: 100, min:0, max: 100, compute: '*1', label: 'qualité'}
#            colfx:
#              - {composite: 'u', command: '--colfx', model: 'range', default: 128, min:0, max: 255, step: 1, compute: '*1', label: 'colorisation'}
#              - {composite: 'v', command: '--colfx', model: 'range', default: 128, min:0, max: 255, step: 1, compute: '*1', label: 'colorisation'}
            iso: { command: '--ISO', model: 'list', default: 1600, collection: [0, 100, 200, 320, 400, 500, 640, 800, 1600], label: 'iso'}
            dcr: { command: '--drc', model: 'list', default: 'off', collection: ['off', 'low', 'med','high'], label: 'compression'}
            metering: { command: '--metering', model: 'list', default: 'matrix', collection: ['average', 'spot', 'backlit', 'matrix'], label: 'mise au point'}
            imxfx: { command: '--imxfx', model: 'list', default: 'none', collection: ['none','negative','solarise','sketch','denoise','emboss','oilpaint','hatch','gpen','pastel','watercolour','film','blur','saturation','colourswap','washedout','posterise','colourpoint','colourbalance','cartoon'], label: 'effet'}
            awb: { command: '--awb', model: 'list', default: 'auto', collection: ['off','auto','sun','cloud','shade','tungsten','fluorescent','incandescent','flash','horizon'], label: 'bal. des blancs'}
            exposure: { command: '--exposure', model: 'list', default: 'auto', collection: ['off','auto','night','nightpreview','backlight','spotlight','sports','snow','beach','verylong','fixedfps','antishake','fireworks'], label: 'exposition'}

services:
    filter_base:
        abstract: true
        arguments: [ '@logger' ]
        tags:
          - { name: 'smilebox.filter'}

    filter_sepia:
        parent: 'filter_base'
        class: 'AppBundle\Model\Filter\SepiaFilter'
    filter_warhol:
        parent: 'filter_base'
        class: 'AppBundle\Model\Filter\WarholFilter'

    gallery:
        class: 'AppBundle\Service\Gallery'
        arguments: ["%output_dir%"]

    pi_camera:
        class: 'AppBundle\Service\PiCamera'
        arguments:
          - '@logger'
          - "%pi_camera%"
          - '@session'
          - "%rpi%"
          - ['@filter_sepia', '@filter_warhol']

    cache_listener:
        class: 'AppBundle\Event\Listener\CacheListener'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }