# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    pi_camera:
        output_dir: '/home/pi/smilebox/web/photos'
        defaults:
            timeout: { command: '--timeout', model: 'range', default: 5000, min:1000, max: 30000, step: 1000, label: 'retardateur'}
            sharpness: { command: '--sharpness', model: 'range', default: 0, min:-100, max: 100, step: 10, label: 'netteté'}
            contrast: { command: '--contrast', model: 'range', default: 0, min:-100, max: 100, step: 10, label: 'contraste'}
            brightness: { command: '--brightness', model: 'range', default: 50, min:0, max: 100, step: 10, label: 'luminosité'}
            saturation: { command: '--saturation', model: 'range', default: 0, min:-100, max: 100, step: 10, label: 'saturation'}
            quality: { command: '--quality', model: 'range', default: 100, min:0, max: 100, label: 'qualité'}
            colfx:
              - {composite: 'u', command: '--colfx', model: 'range', default: 128, min:0, max: 255, step: 1, label: 'colorisation'}
              - {composite: 'v', command: '--colfx', model: 'range', default: 128, min:0, max: 255, step: 1, label: 'colorisation'}
            iso: { command: '--ISO', model: 'list', default: 0, collection: [0, 100, 200, 320, 400, 500, 640, 800, 1600], label: 'iso'}
            dcr: { command: '--drc', model: 'list', default: 'off', collection: ['off', 'low', 'med','high'], label: 'compression'}
            metering: { command: '--metering', model: 'list', default: 'matrix', collection: ['average', 'spot', 'backlit', 'matrix'], label: 'mise au point'}
            imxfx: { command: '--imxfx', model: 'list', default: 'none', collection: ['none','negative','solarise','sketch','denoise','emboss','oilpaint','hatch','gpen','pastel','watercolour','film','blur','saturation','colourswap','washedout','posterise','colourpoint','colourbalance','cartoon'], label: 'effet'}
            awb: { command: '--awb', model: 'list', default: 'off', collection: ['off','auto','sun','cloud','shade','tungsten','fluorescent','incandescent','flash','horizon'], label: 'bal. des blancs'}
            exposure: { command: '--exposure', model: 'list', default: 'off', collection: ['off','auto','night','nightpreview','backlight','spotlight','sports','snow','beach','verylong','fixedfps','antishake','fireworks'], label: 'exposition'}

services:
    pi_camera:
        class: AppBundle\Service\PiCamera
        arguments: ["%pi_camera%", '@session']
        calls:
          - ['setLogger', ['@logger']]
